[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "GreenTensor"
authors = [{name = "Denisov", email = "denisov.dv55@gmail"}]
dynamic = ["version", "description"]